version: '3'
services:

  basketserver:
    build:
      context: basket
    ports:
    - 8181:8181
    network_mode: host

  clientrest:
    build:
      context: clientrest
    ports:
    - 8080:8080
    depends_on:
      - basketserver
    network_mode: host
